**Import library**

In [17]:
import pandas as pd
import numpy as np

**Data loading**

In [18]:
customers = pd.read_csv("Downloads/Quickbite/customers.csv")
restaurants = pd.read_csv("Downloads/Quickbite/restaurants.csv")
menu_items = pd.read_csv("Downloads/Quickbite/menu_items.csv")
orders = pd.read_csv("Downloads/Quickbite/orders.csv")
payments = pd.read_csv("Downloads/Quickbite/payments.csv")

**Data Understanding**

In [19]:
print("Customers shape:", customers.shape)
customers.head()

Customers shape: (25, 5)

   customer_id customer_name       city signup_date customer_segment
0            1  Aarav Sharma  Bengaluru  10-01-2025          Premium
1            2     Diya Iyer     Mumbai  18-01-2025          Regular
2            3   Rohan Mehta      Delhi  02-02-2025          Premium
3            4    Ananya Rao  Bengaluru  15-02-2025              New
4            5  Vikram Singh       Pune  20-02-2025          Regular

In [20]:
print("Customers shape:", customers.shape)
customers.head()

Customers shape: (25, 5)

   customer_id customer_name       city signup_date customer_segment
0            1  Aarav Sharma  Bengaluru  10-01-2025          Premium
1            2     Diya Iyer     Mumbai  18-01-2025          Regular
2            3   Rohan Mehta      Delhi  02-02-2025          Premium
3            4    Ananya Rao  Bengaluru  15-02-2025              New
4            5  Vikram Singh       Pune  20-02-2025          Regular

In [21]:
print("Restaurants shape:", restaurants.shape)
restaurants.head()

Restaurants shape: (20, 5)

   restaurant_id restaurant_name       city       cuisine  rating
0              1     Spice Route  Bengaluru        Indian     4.5
1              2      Burger Hub     Mumbai     Fast Food     4.2
2              3  Tandoori Tales      Delhi  North Indian     4.6
3              4     Dosa Corner    Chennai  South Indian     4.4
4              5    Bengal Spice    Kolkata       Bengali     4.3

In [22]:
print("Menu Items shape:", menu_items.shape)
menu_items.head()

Menu Items shape: (40, 5)

   item_id  restaurant_id item_name     category   price
0        1              1    Item 1  Main Course  458.90
1        2              2    Item 2      Starter  133.26
2        3              3    Item 3     Beverage  265.77
3        4              4    Item 4      Dessert  238.30
4        5              5    Item 5  Main Course  510.33

In [23]:
print("Orders shape:", orders.shape)
orders.head()

Orders shape: (50, 8)

,order_id,customer_id,restaurant_id,order_date,order_status,delivery_minutes,order_amount,discount
0,1,13,15,19-06-2025,Delivered,36.0,466.43,75
1,2,18,18,04-07-2025,Delivered,67.0,1156.11,50
2,3,13,12,29-06-2025,Delivered,28.0,1039.77,0
3,4,25,2,19-09-2025,Delivered,27.0,486.90,0
4,5,22,14,16-08-2025,Pending,24.0,846.39,50

In [24]:
print("Payments shape:", payments.shape)
payments.head()

Payments shape: (50, 5)

   payment_id  order_id payment_method payment_status payment_date
0           1         1    Credit Card           Paid   2025-06-19
1           2         2           Cash        Pending   2025-07-04
2           3         3            UPI           Paid   2025-06-29
3           4         4    Credit Card           Paid   2025-09-19
4           5         5     Debit Card           Paid   2025-08-16

**Check Column Names**

In [25]:
print("Customers columns:\n", customers.columns)
print("\nRestaurants columns:\n", restaurants.columns)
print("\nMenu Items columns:\n", menu_items.columns)
print("\nOrders columns:\n", orders.columns)
print("\nPayments columns:\n", payments.columns)

Customers columns:
 Index(['customer_id', 'customer_name', 'city', 'signup_date',
       'customer_segment'],
      dtype='object')

Restaurants columns:
 Index(['restaurant_id', 'restaurant_name', 'city', 'cuisine', 'rating'], dtype='object')

Menu Items columns:
 Index(['item_id', 'restaurant_id', 'item_name', 'category', 'price'], dtype='object')

Orders columns:
 Index(['order_id', 'customer_id', 'restaurant_id', 'order_date',
       'order_status', 'delivery_minutes', 'order_amount', 'discount'],
      dtype='object')

Payments columns:
 Index(['payment_id', 'order_id', 'payment_method', 'payment_status',
       'payment_date'],
      dtype='object')

**Check Data Types and Non-Null Counts**

In [26]:
print("--- Customers Info ---")
customers.info()

print("\n--- Restaurants Info ---")
restaurants.info()

print("\n--- Menu Items Info ---")
menu_items.info()

print("\n--- Orders Info ---")
orders.info()

print("\n--- Payments Info ---")
payments.info()

--- Customers Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       25 non-null     int64
 1   customer_name     25 non-null     object
 2   city              25 non-null     object
 3   signup_date       25 non-null     object
 4   customer_segment  24 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.1+ KB

--- Restaurants Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   restaurant_id    20 non-null     int64
 1   restaurant_name  20 non-null     object
 2   city             20 non-null     object
 3   cuisine          20 non-null     object
 4   rating           20 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 932.0+ bytes

--- Menu Items Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   item_id        40 non-null     int64
 1   restaurant_id  40 non-null     int64
 2   item_name      40 non-null     object
 3   category       40 non-null     object
 4   price          40 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.7+ KB

--- Orders Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50 non-null     int64
 1   customer_id       50 non-null     int64
 2   restaurant_id     50 non-null     int64
 3   order_date        50 non-null     object
 4   order_status      50 non-null     object
 5   delivery_minutes  44 non-null     float64
 6   order_amount      50 non-null     float64
 7   discount          50 non-null     int64
dtypes: float64(2), int64(4), object(2)
memory usage: 3.3+ KB

--- Payments Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      50 non-null     int64
 1   order_id        50 non-null     int64
 2   payment_method  50 non-null     object
 3   payment_status  50 non-null     object
 4   payment_date    50 non-null     object
dtypes: int64(2), object(3)
memory usage: 2.1+ KB

**Check Missing Values**

In [27]:
print("Customers Missing Values:\n", customers.isnull().sum())
print("\nRestaurants Missing Values:\n", restaurants.isnull().sum())
print("\nMenu Items Missing Values:\n", menu_items.isnull().sum())
print("\nOrders Missing Values:\n", orders.isnull().sum())
print("\nPayments Missing Values:\n", payments.isnull().sum())

Customers Missing Values:
 customer_id         0
customer_name       0
city                0
signup_date         0
customer_segment    1
dtype: int64

Restaurants Missing Values:
 restaurant_id      0
restaurant_name    0
city               0
cuisine            0
rating             0
dtype: int64

Menu Items Missing Values:
 item_id          0
restaurant_id    0
item_name        0
category         0
price            0
dtype: int64

Orders Missing Values:
 order_id            0
customer_id         0
restaurant_id       0
order_date          0
order_status        0
delivery_minutes    6
order_amount        0
discount            0
dtype: int64

Payments Missing Values:
 payment_id        0
order_id          0
payment_method    0
payment_status    0
payment_date      0
dtype: int64

**Check Duplicate Rows**

In [28]:
print("Customers duplicates:", customers.duplicated().sum())
print("Restaurants duplicates:", restaurants.duplicated().sum())
print("Menu Items duplicates:", menu_items.duplicated().sum())
print("Orders duplicates:", orders.duplicated().sum())
print("Payments duplicates:", payments.duplicated().sum())

Customers duplicates: 0
Restaurants duplicates: 0
Menu Items duplicates: 0
Orders duplicates: 0
Payments duplicates: 0

**Data Quality Analysis Summary**

In [29]:
summary = pd.DataFrame({
    "Table": ["Customers", "Restaurants", "Menu Items", "Orders", "Payments"],
    "Missing Values": [
        customers.isnull().sum().sum(),
        restaurants.isnull().sum().sum(),
        menu_items.isnull().sum().sum(),
        orders.isnull().sum().sum(),
        payments.isnull().sum().sum()
    ],
    "Duplicate Rows": [
        customers.duplicated().sum(),
        restaurants.duplicated().sum(),
        menu_items.duplicated().sum(),
        orders.duplicated().sum(),
        payments.duplicated().sum()
    ]
})

summary["Action"] = summary.apply(
    lambda row: "Clean" if row["Missing Values"] > 0 or row["Duplicate Rows"] > 0 else "Good",
    axis=1
)
summary

         Table  Missing Values  Duplicate Rows Action
0    Customers               1               0  Clean
1  Restaurants               0               0   Good
2   Menu Items               0               0   Good
3       Orders               6               0  Clean
4     Payments               0               0   Good

**Clean Customer Datset**

In [30]:
# Create a working copy
customers_clean = customers.copy()

# Ensure customer_id is integer
customers_clean["customer_id"] = pd.to_numeric(customers_clean["customer_id"], errors="coerce")
customers_clean = customers_clean[customers_clean["customer_id"].notnull()]
customers_clean["customer_id"] = customers_clean["customer_id"].astype(int)

# Convert signup_date to datetime
customers_clean["signup_date"] = pd.to_datetime(customers_clean["signup_date"], dayfirst=True, errors="coerce")

# Handle missing values in customer_segment (fill missing with 'Unknown' or mode)
customers_clean["customer_segment"] = customers_clean["customer_segment"].fillna("Unknown")

# Strip leading/trailing whitespaces in categorical text
customers_clean["customer_name"] = customers_clean["customer_name"].str.strip()
customers_clean["city"] = customers_clean["city"].str.strip()
customers_clean["customer_segment"] = customers_clean["customer_segment"].str.strip()

# Verification check
print("Cleaned Customers Shape:", customers_clean.shape)
print(customers_clean.isnull().sum())

Cleaned Customers Shape: (25, 5)
customer_id         0
customer_name       0
city                0
signup_date         0
customer_segment    0
dtype: int64

**Clean Restaurant & Menu Items Datasets**

In [32]:
restaurants_clean = restaurants.copy()

# Ensure primary key is integer
restaurants_clean["restaurant_id"] = restaurants_clean["restaurant_id"].astype(int)

# Text standardization
restaurants_clean["restaurant_name"] = restaurants_clean["restaurant_name"].str.strip()
restaurants_clean["city"] = restaurants_clean["city"].str.strip()
restaurants_clean["cuisine"] = restaurants_clean["cuisine"].str.strip()

# Verify rating range (1.0 to 5.0)
print("Restaurant Rating Summary:")
print(restaurants_clean["rating"].describe())

Restaurant Rating Summary:
count    20.000000
mean      4.325000
std       0.207428
min       4.000000
25%       4.175000
50%       4.350000
75%       4.500000
max       4.700000
Name: rating, dtype: float64

In [36]:
menu_items_clean = menu_items.copy()

# Ensure keys and types
menu_items_clean["item_id"] = menu_items_clean["item_id"].astype(int)
menu_items_clean["restaurant_id"] = menu_items_clean["restaurant_id"].astype(int)
menu_items_clean["item_name"] = menu_items_clean["item_name"].str.strip()
menu_items_clean["category"] = menu_items_clean["category"].str.strip()

# Verify price validity (no zero or negative prices)
print("Menu Items Price Summary:")
print(menu_items_clean["price"].describe())
print("\nItems with price <= 0:", (menu_items_clean["price"] <= 0).sum())

Menu Items Price Summary:
count     40.000000
mean     379.361250
std      158.143679
min      123.440000
25%      236.592500
50%      410.700000
75%      507.652500
max      635.750000
Name: price, dtype: float64

Items with price <= 0: 0

**Clean Orders Dataset**

In [37]:
orders_clean = orders.copy()

# Convert order_date to datetime format
orders_clean["order_date"] = pd.to_datetime(orders_clean["order_date"], dayfirst=True, errors="coerce")

# Ensure numeric datatypes
orders_clean["order_id"] = orders_clean["order_id"].astype(int)
orders_clean["customer_id"] = orders_clean["customer_id"].astype(int)
orders_clean["restaurant_id"] = orders_clean["restaurant_id"].astype(int)

# Standardize string fields
orders_clean["order_status"] = orders_clean["order_status"].str.strip()

# Handle missing delivery_minutes
# Notice missing delivery_minutes belong to Cancelled orders: impute with 0 or a sentinel value
orders_clean["delivery_minutes"] = orders_clean["delivery_minutes"].fillna(0)

# Check order_amount and discount validity
print("Orders Summary:")
print(orders_clean[["delivery_minutes", "order_amount", "discount"]].describe())
print("\nOrders where discount exceeds order_amount:", (orders_clean["discount"] > orders_clean["order_amount"]).sum())

Orders Summary:
       delivery_minutes  order_amount    discount
count         50.000000     50.000000   50.000000
mean          43.100000    956.794600   31.900000
std           21.359173    466.565015   37.360489
min            0.000000    333.970000    0.000000
25%           32.000000    507.027500    0.000000
50%           45.500000    921.010000   20.000000
75%           61.750000   1374.622500   68.750000
max           70.000000   1777.230000  100.000000

Orders where discount exceeds order_amount: 0

**Clean Payments Dataset**

In [38]:
payments_clean = payments.copy()

# Convert IDs and Dates
payments_clean["payment_id"] = payments_clean["payment_id"].astype(int)
payments_clean["order_id"] = payments_clean["order_id"].astype(int)
payments_clean["payment_date"] = pd.to_datetime(payments_clean["payment_date"], errors="coerce")

# Clean text categories
payments_clean["payment_method"] = payments_clean["payment_method"].str.strip()
payments_clean["payment_status"] = payments_clean["payment_status"].str.strip()

print("Cleaned Payments Shape:", payments_clean.shape)
print(payments_clean.isnull().sum())

Cleaned Payments Shape: (50, 5)
payment_id        0
order_id          0
payment_method    0
payment_status    0
payment_date      0
dtype: int64

**Validate Relational Integrity (Foreign Keys)**

In [39]:
# Check 1: Do all customer_ids in orders exist in customers?
invalid_customers = orders_clean[~orders_clean["customer_id"].isin(customers_clean["customer_id"])]
print("Orders with invalid customer_id:", len(invalid_customers))

# Check 2: Do all restaurant_ids in orders exist in restaurants?
invalid_restaurants = orders_clean[~orders_clean["restaurant_id"].isin(restaurants_clean["restaurant_id"])]
print("Orders with invalid restaurant_id:", len(invalid_restaurants))

# Check 3: Do all order_ids in payments exist in orders?
invalid_payments = payments_clean[~payments_clean["order_id"].isin(orders_clean["order_id"])]
print("Payments with invalid order_id:", len(invalid_payments))

# Check 4: Do all restaurant_ids in menu_items exist in restaurants?
invalid_menu_restaurants = menu_items_clean[~menu_items_clean["restaurant_id"].isin(restaurants_clean["restaurant_id"])]
print("Menu items with invalid restaurant_id:", len(invalid_menu_restaurants))

Orders with invalid customer_id: 0
Orders with invalid restaurant_id: 0
Payments with invalid order_id: 0
Menu items with invalid restaurant_id: 0

**Export Cleaned Datasets**

**Save Cleaned Datasets into CSV Files**

In [40]:
# Cell 35 (Code)
customers_clean.to_csv("Cleaned_Customers.csv", index=False)
restaurants_clean.to_csv("Cleaned_Restaurants.csv", index=False)
menu_items_clean.to_csv("Cleaned_Menu_Items.csv", index=False)
orders_clean.to_csv("Cleaned_Orders.csv", index=False)
payments_clean.to_csv("Cleaned_Payments.csv", index=False)

print("All cleaned datasets successfully exported to CSV!")

All cleaned datasets successfully exported to CSV!